// Finanzlexikon: kurze, allgemeine Erklärungen. "l" verweist auf eine passende Lektion.

export interface Term { t: string; d: string; l?: string }

export const GLOSSARY: Term[] = [
  { t: "Abgeltungsteuer", d: "Pauschale Steuer von 25 % auf Kapitalerträge wie Zinsen, Dividenden und Kursgewinne, zuzüglich Soli und gegebenenfalls Kirchensteuer.", l: "t1" },
  { t: "Aktie", d: "Anteil an einem Unternehmen. Aktionäre sind Miteigentümer und am Gewinn und Risiko beteiligt.", l: "i1" },
  { t: "Anleihe", d: "Verzinster Kredit an einen Staat oder ein Unternehmen, der nach einer festen Laufzeit zurückgezahlt wird.", l: "x4" },
  { t: "Ausgabeaufschlag", d: "Einmalige Gebühr beim Kauf vieler aktiv gemanagter Fonds, oft einige Prozent des Anlagebetrags.", l: "g1" },
  { t: "Ausschüttend", d: "Ein Fonds, der Dividenden und Zinsen regelmäßig an die Anleger auszahlt.", l: "i4" },
  { t: "BaFin", d: "Bundesanstalt für Finanzdienstleistungsaufsicht. Sie beaufsichtigt Banken, Versicherer und Finanzdienstleister in Deutschland und warnt vor unseriösen Anbietern.", l: "f3" },
  { t: "Basiskonto", d: "Girokonto mit grundlegenden Funktionen, auf das jeder Verbraucher mit Wohnsitz in der EU einen Anspruch hat.", l: "b3" },
  { t: "Berufsunfähigkeitsversicherung", d: "Zahlt eine monatliche Rente, wenn du deinen Beruf aus gesundheitlichen Gründen längere Zeit nicht mehr ausüben kannst.", l: "v4" },
  { t: "BIP", d: "Bruttoinlandsprodukt: Wert aller Waren und Dienstleistungen, die in einem Land in einem Zeitraum hergestellt werden.", l: "w2" },
  { t: "Bonität", d: "Kreditwürdigkeit: wie zuverlässig jemand Schulden zurückzahlt.", l: "k4" },
  { t: "Cost-Average-Effekt", d: "Wer regelmäßig einen festen Betrag anlegt, kauft bei niedrigen Kursen mehr und bei hohen weniger Anteile.", l: "z2" },
  { t: "DAX", d: "Deutscher Aktienindex mit den 40 größten börsennotierten Unternehmen Deutschlands.", l: "w3" },
  { t: "Depot", d: "Konto zur Verwahrung von Wertpapieren wie Aktien und ETFs. Die Wertpapiere bleiben dein Eigentum.", l: "i5" },
  { t: "Dispositionskredit", d: "Überziehungsrahmen auf dem Girokonto. Bequem, aber meist sehr teuer.", l: "b2" },
  { t: "Diversifikation", d: "Streuung des Geldes auf viele Anlagen, um das Risiko einzelner Verluste zu senken.", l: "i3" },
  { t: "Dividende", d: "Gewinnausschüttung eines Unternehmens an seine Aktionäre.", l: "x2" },
  { t: "Effektiver Jahreszins", d: "Zinssatz eines Kredits inklusive aller Kosten. Damit lassen sich Kreditangebote vergleichen.", l: "b2" },
  { t: "Einlagensicherung", d: "Gesetzlicher Schutz von Bankguthaben bis 100.000 € pro Person und Bank in der EU.", l: "s1" },
  { t: "Entgeltumwandlung", d: "Ein Teil des Bruttogehalts fließt direkt in eine Betriebsrente. Der Arbeitgeber gibt in der Regel einen Zuschuss dazu.", l: "v3" },
  { t: "ESG", d: "Umwelt, Soziales und Unternehmensführung: Kriterien für nachhaltige Geldanlagen.", l: "o1" },
  { t: "ETF", d: "Börsengehandelter Fonds, der einen Index nachbildet. Günstig und breit gestreut.", l: "i2" },
  { t: "EZB", d: "Europäische Zentralbank. Sie legt die Leitzinsen für den Euroraum fest und soll die Preise stabil halten.", l: "w1" },
  { t: "Festgeld", d: "Geldanlage mit fester Laufzeit und festem Zins. Während der Laufzeit kommst du in der Regel nicht an das Geld.", l: "s3" },
  { t: "Freistellungsauftrag", d: "Auftrag an die Bank, Kapitalerträge bis zum Sparerpauschbetrag nicht zu besteuern.", l: "t4" },
  { t: "Girokonto", d: "Konto für den Zahlungsverkehr: Gehalt, Überweisungen, Lastschriften und Kartenzahlungen.", l: "b3" },
  { t: "Greenwashing", d: "Ein Produkt wird umweltfreundlicher dargestellt, als es tatsächlich ist.", l: "o2" },
  { t: "Index", d: "Kennzahl, die die Kursentwicklung einer Gruppe von Aktien oder anderen Wertpapieren abbildet.", l: "w3" },
  { t: "Inflation", d: "Anstieg des allgemeinen Preisniveaus. Geld verliert dadurch Kaufkraft.", l: "s2" },
  { t: "KGV", d: "Kurs-Gewinn-Verhältnis: Aktienkurs geteilt durch den Gewinn pro Aktie.", l: "x1" },
  { t: "Klumpenrisiko", d: "Risiko, das entsteht, wenn viel Geld in einer einzigen oder wenigen ähnlichen Anlagen steckt.", l: "i3" },
  { t: "Kleinunternehmerregelung", d: "Befreiung kleiner Unternehmen von der Umsatzsteuer, wenn der Umsatz bestimmte Grenzen nicht überschreitet.", l: "n2" },
  { t: "Konditionsanfrage", d: "Anfrage nach Kreditkonditionen, die den Schufa-Score nicht beeinflusst.", l: "k4" },
  { t: "Leitzins", d: "Zinssatz, zu dem sich Banken bei der Zentralbank Geld leihen oder parken können. Er beeinflusst alle anderen Zinsen.", l: "w1" },
  { t: "Liquidität", d: "Wie schnell und einfach sich eine Anlage in Bargeld umwandeln lässt.", l: "z3" },
  { t: "Limit-Order", d: "Kauf- oder Verkaufsauftrag mit festgelegter Preisgrenze.", l: "x3" },
  { t: "Minijob", d: "Beschäftigung mit geringem Verdienst bis zu einer monatlichen Grenze, für Beschäftigte weitgehend abgabenfrei.", l: "a1" },
  { t: "MSCI World", d: "Aktienindex mit großen und mittelgroßen Unternehmen aus 23 Industrieländern.", l: "i2" },
  { t: "Notgroschen", d: "Rücklage für unerwartete Ausgaben, meist drei bis sechs Monatsausgaben auf dem Tagesgeldkonto.", l: "s1" },
  { t: "P-Konto", d: "Pfändungsschutzkonto, das einen Grundbetrag für den Lebensunterhalt vor Pfändung schützt.", l: "k2" },
  { t: "Phishing", d: "Betrugsversuch mit gefälschten E-Mails, SMS oder Websites, um Zugangsdaten zu stehlen.", l: "f1" },
  { t: "Realzins", d: "Zins nach Abzug der Inflation. Er zeigt, ob die Kaufkraft wirklich wächst.", l: "z5" },
  { t: "Rebalancing", d: "Wiederherstellen der geplanten Aufteilung eines Depots, etwa zwischen Aktien und sicheren Anlagen.", l: "g4" },
  { t: "Rendite", d: "Ertrag einer Geldanlage im Verhältnis zum eingesetzten Kapital, meist pro Jahr in Prozent.", l: "z3" },
  { t: "Rentenlücke", d: "Differenz zwischen gesetzlicher Rente und dem Einkommen, das man im Alter für seinen Lebensstandard braucht.", l: "v1" },
  { t: "Rezession", d: "Phase, in der die Wirtschaftsleistung sinkt. Meist spricht man davon, wenn das BIP zwei Quartale in Folge schrumpft.", l: "w2" },
  { t: "Riester-Rente", d: "Staatlich geförderte private Altersvorsorge mit Zulagen und Steuervorteilen.", l: "v5" },
  { t: "Rürup-Rente", d: "Basisrente mit steuerlich absetzbaren Beiträgen, vor allem für Selbstständige und Gutverdiener.", l: "v5" },
  { t: "Schufa", d: "Auskunftei, die Daten zum Zahlungsverhalten sammelt und daraus einen Score zur Kreditwürdigkeit berechnet.", l: "b2" },
  { t: "Sondervermögen", d: "Vermögen, das rechtlich vom Vermögen eines Anbieters getrennt ist, etwa Fondsanteile im Depot.", l: "i5" },
  { t: "Sparerpauschbetrag", d: "Freibetrag für Kapitalerträge: 1.000 € im Jahr, bei Zusammenveranlagung 2.000 €.", l: "t1" },
  { t: "Sparplan", d: "Regelmäßige, automatische Geldanlage, etwa monatlich in einen ETF.", l: "i5" },
  { t: "Tagesgeld", d: "Verzinstes Konto, auf dessen Guthaben du jederzeit zugreifen kannst.", l: "s3" },
  { t: "TER", d: "Total Expense Ratio: laufende Kosten eines Fonds pro Jahr in Prozent.", l: "i2" },
  { t: "Thesaurierend", d: "Ein Fonds, der Erträge automatisch wieder anlegt, statt sie auszuzahlen.", l: "i4" },
  { t: "Tilgung", d: "Rückzahlung eines Kredits. Sie ist neben den Zinsen Teil der monatlichen Rate.", l: "k3" },
  { t: "Tracking Difference", d: "Tatsächliche Abweichung der Wertentwicklung eines ETFs von seinem Index nach allen Kosten.", l: "g2" },
  { t: "Vermögenswirksame Leistungen", d: "Zuschuss des Arbeitgebers zum Sparen, oft bis zu 40 € im Monat, je nach Vertrag.", l: "s6" },
  { t: "Volatilität", d: "Maß dafür, wie stark der Preis einer Anlage schwankt.", l: "i7" },
  { t: "Vorabpauschale", d: "Jährlich berechneter Mindestertrag bei Fonds, auf den Steuern anfallen können. Wird beim Verkauf angerechnet.", l: "t4" },
  { t: "Werbungskosten", d: "Ausgaben für den Beruf, die das zu versteuernde Einkommen senken, etwa Fahrtkosten oder Arbeitsmittel.", l: "t2" },
  { t: "Widerrufsrecht", d: "Recht, online oder an der Haustür geschlossene Verträge meist innerhalb von 14 Tagen ohne Grund zu widerrufen.", l: "a3" },
  { t: "Zinseszins", d: "Zinsen, die auf bereits gutgeschriebene Zinsen entstehen. Über lange Zeit ein starker Effekt.", l: "z1" },
  { t: "Zinsbindung", d: "Zeitraum, für den der Zins eines Kredits fest vereinbart ist.", l: "k3" },
];
